### ISSUE TITLE
Ease of use to people on windows platforms !

### ISSUE THREAD

**Issue by gxhamster** [GDQuest/product-packager#12]
Can we have a python version of these packaging tools

**Comment by NathanLovato** [comment]
No, we're not going to rewrite everything in Python. Not only do we have a lot of work, but this would be a less convenient language for the job. Bash is available on Windows all the same, even officially supported through the Windows Subsystem for Linux.

https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

If you don't want to install a complete Linux image, git bash, cygwin are two other options that should work. If you have git installed on your computer, you should also have git bash.

You can install it through the full version of cmder, one of the best terminal emulators I've seen and used on Windows: https://cmder.net/
