### ISSUE TITLE
Write a tool to highlight (gdscript) code with chroma

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/product-packager#16]
Pandoc's syntax highlighter doesn't support GDScript, so we need a dedicated tool to do that. [Chroma](https://github.com/alecthomas/chroma/) does and it's great.

We need a tool that can:

- Find (gdscript) code snippets in our [html] documents
- Replace the raw code with chroma's output

We can do it either from the markdown documents, before running pandoc, or in the output html.

The only gotcha with html is that pandoc replaces special characters like `>` with `&gt;`, etc., so we would need to replace them.

In either case, this seems like a good candidate for a Python program

**Comment by NathanLovato** [comment]
Actually, we need to do it with the markdown: doing it with the html output wouldn't work when converting markdown to pdf, epub, etc.

**Comment by razcore-art** [comment]
I was looking at the CSS and saw this issue. I think it's much simpler to just use the `--syntax-definition=FILE` option https://pandoc.org/MANUAL.html#option--syntax-definition. We just need to define a GDScript `xml` file which seems pretty simple.

**Comment by NathanLovato** [comment]
That issue is already done since a long time. It's working well already, so I don't want us to change tool now. For me writing the syntax + css for pandoc would've taken more time.

**Comment by davcri** [comment]
> I was looking at the CSS and saw this issue. I think it's much simpler to just use the `--syntax-definition=FILE` option https://pandoc.org/MANUAL.html#option--syntax-definition. We just need to define a GDScript `xml` file which seems pretty simple.

Just FYI: now there is an upstream syntax definition file in [KDE/syntax-highlighting/blob/master/data/syntax/gd-script.xml](https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/gd-script.xml).
