### ISSUE TITLE
Formatter doesn't format this sentence

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/product-packager#51]
> As we've seen, every Resource has a resource_path property, the path to the resource's file.

Full document: 

[06.customizing-the-character-in-a-menu.md](https://github.com/GDQuest/product-packager/files/8749178/06.customizing-the-character-in-a-menu.md)

**Comment by razcore-rad** [comment]
Yea, it seems this happens because of the `'` characters cause we skip quoted strings and other such stuff. So removing one of them applies formatting correctly. I'll have to think about this one

**Comment by razcore-rad** [comment]
For now I added `v` to the negative test, this seems to work and cover most cases `'(?![vsr\h]).+?'`.
