### ISSUE TITLE
Write a program that processes include shortcodes and adds icon tags

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/product-packager#54]
For the new web platform, we need a pre-processing step between the written content and the website build.

Before every build, we need to include the latest version of source code files. We want to keep working with {{ include }} shortcodes in the courses' source content and replace them every time we want to build the website.

The flow to build the website will thus be:

1. Run this program to make a new copy of the markdown content with the includes replaced with the appropriate code and icon components added before relevant node names. This copy should come with all the images and media files the markdown documents require.
2.  Build the website with the pre processed content.

This task is about building step 1.

It could:

1. Make a copy of the content/ folder of a given course.
2. Process markdown files in-place in the copied folder.
    - Replace include shortcodes as usual.
    - Add tags with the form `<Icon name="icon-file-name" /> before `NodeName`. 

We'll call the program as part of a build script, and we'll want to have the ability to run it from the web platform's repository, so we should be able to tell the program:

- The source folder to process
- The output folder

Because the web platform looks for the content in specific folders.

**Comment by razcore-rad** [comment]
To complete this task I need to:

1. copy the code, icons, and whatever other resources we require
2. handle image links/slug if necessary, based on the discussion on Discord
